image: rocker/r-base:latest

pages:
  stage: deploy
  
  before_script:
    - apt-get update -qq
    - apt-get install -t unstable software-properties-common --yes
    - apt-get install -t unstable --yes libssl-dev libssh2-1-dev libxml2-dev libcurl4-gnutls-dev libgit2-dev libmagick++-dev pandoc pandoc-citeproc

  script:
    - Rscript -e 'install.packages("devtools")'
    - Rscript -e 'install.packages("shiny")'
    - Rscript -e 'devtools::install_github("r-lib/pkgdown")'
    - Rscript -e 'devtools::install_git("https://gitlab.com/dickoa/shinyuikit")'
    - Rscript -e 'pkgdown::build_site()'
    - mv docs public
    

  artifacts:
    paths:
      - public
